# Generated by Django 5.0.2 on 2024-02-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='adress',
            new_name='address',
        ),
    ]
