// actionTypes.js

export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST';
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';
export const CREATE_RESERVATION_FAIL = 'CREATE_RESERVATION_FAIL';
export const CREATE_RESERVATION_RESET = 'CREATE_RESERVATION_RESET';
export const RESERVATION_LIST_REQUEST = 'RESERVATION_LIST_REQUEST';
export const RESERVATION_LIST_SUCCESS = 'RESERVATION_LIST_SUCCESS';
export const RESERVATION_LIST_FAIL = 'RESERVATION_LIST_FAIL';

export const RESERVATION_DETAILS_REQUEST = 'RESERVATION_DETAILS_REQUEST';
export const RESERVATION_DETAILS_SUCCESS = 'RESERVATION_DETAILS_SUCCESS';
export const RESERVATION_DETAILS_FAIL = 'RESERVATION_DETAILS_FAIL';
export const UPDATE_CHECKIN_PROCESS_REQUEST = 'UPDATE_CHECKIN_PROCESS_REQUEST';
export const UPDATE_CHECKIN_PROCESS_SUCCESS = 'UPDATE_CHECKIN_PROCESS_SUCCESS';
export const UPDATE_CHECKIN_PROCESS_FAIL = 'UPDATE_CHECKIN_PROCESS_FAIL';
