# Generated by Django 5.0.3 on 2024-03-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
