# Generated by Django 5.0.3 on 2024-03-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='branchaddress',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='base.branchaddress'),
        ),
    ]
