# Generated by Django 5.0.3 on 2024-04-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_payment'),
        ('base', '0009_remove_branchaddress_order_branchaddress_branch_name_and_more'),
    ]

    operations = [
    ]
